name: Deploy to Kubernetes
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config ; chmod 600 $HOME/.kube/config
          kubectl get pods 

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/taidomi-sapi-de-cv/website:${{ github.sha }}
          build-args: |
            REACT_APP_BACKEND_URL=https://domitai.com/api/v2
            NODE_ENV=dev

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.15.0'

      #      - name: Configure kubeconfig
      #        env:
      #          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #        run: |
      #          mkdir -p $HOME/.kube
      #          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install website ./helm-chart \
            -n domitai --create-namespace \
            --set image.repository=ghcr.io/taidomi-sapi-de-cv/website \
            --set image.tag=${{ github.sha }} \
            --reuse-values
